# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 631)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.vDockPlatform = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vDockPlatform.sizePolicy().hasHeightForWidth())
        self.vDockPlatform.setSizePolicy(sizePolicy)
        self.vDockPlatform.setMinimumSize(QtCore.QSize(200, 111))
        self.vDockPlatform.setMaximumSize(QtCore.QSize(500, 524287))
        self.vDockPlatform.setBaseSize(QtCore.QSize(200, 0))
        self.vDockPlatform.setStyleSheet("")
        self.vDockPlatform.setFloating(False)
        self.vDockPlatform.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.vDockPlatform.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.vDockPlatform.setWindowTitle("")
        self.vDockPlatform.setObjectName("vDockPlatform")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vPlatformTree = QtWidgets.QTreeWidget(self.dockWidgetContents_6)
        self.vPlatformTree.setStyleSheet("")
        self.vPlatformTree.setObjectName("vPlatformTree")
        item_0 = QtWidgets.QTreeWidgetItem(self.vPlatformTree)
        item_0 = QtWidgets.QTreeWidgetItem(self.vPlatformTree)
        item_0 = QtWidgets.QTreeWidgetItem(self.vPlatformTree)
        item_0 = QtWidgets.QTreeWidgetItem(self.vPlatformTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_2.addWidget(self.vPlatformTree)
        self.vDockPlatform.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.vDockPlatform)
        self.vDockFuncs = QtWidgets.QDockWidget(MainWindow)
        self.vDockFuncs.setObjectName("vDockFuncs")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents_2)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.listWidget)
        self.vDockFuncs.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.vDockFuncs)
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionClose_Project = QtWidgets.QAction(MainWindow)
        self.actionClose_Project.setObjectName("actionClose_Project")
        self.menu.addAction(self.actionNew_Project)
        self.menu.addAction(self.actionOpen_Project)
        self.menu.addAction(self.actionClose_Project)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.vPlatformTree.headerItem().setText(0, _translate("MainWindow", "platform"))
        __sortingEnabled = self.vPlatformTree.isSortingEnabled()
        self.vPlatformTree.setSortingEnabled(False)
        self.vPlatformTree.topLevelItem(0).setText(0, _translate("MainWindow", "c/c++"))
        self.vPlatformTree.topLevelItem(1).setText(0, _translate("MainWindow", "Java"))
        self.vPlatformTree.topLevelItem(2).setText(0, _translate("MainWindow", "Python"))
        self.vPlatformTree.topLevelItem(3).setText(0, _translate("MainWindow", "Android"))
        self.vPlatformTree.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "UI"))
        self.vPlatformTree.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "xml->ViewHolder"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionClose_Project.setText(_translate("MainWindow", "Close Project"))

